# Generated by Django 5.2.1 on 2025-11-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traystatus',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
