# Generated by Django 5.2.1 on 2025-11-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_traystatus_tray_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], max_length=3)),
                ('timestamp', models.DateTimeField()),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.traystatus')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
