# Generated by Django 5.2.1 on 2025-12-07 12:55

import services.data_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0009_stockinentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='expiry_date',
            field=models.DateField(default=services.data_storage.models.default_expiry_date),
        ),
    ]
