# Generated by Django 5.2.1 on 2025-11-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_traystatus_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traystatus',
            name='tray_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='traystatus',
            constraint=models.UniqueConstraint(fields=('tray_id', 'topic'), name='unique_tray_topic'),
        ),
    ]
