# Generated by Django 5.2.9 on 2026-01-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_traystatus_last_alert_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrayHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray_id', models.CharField(max_length=64)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tray_id'],
                'constraints': [models.UniqueConstraint(fields=('tray_id', 'topic'), name='unique_tray_heartbeat')],
            },
        ),
        migrations.CreateModel(
            name='TrayHeartbeatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('down', 'Down')], max_length=8)),
                ('timestamp', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('heartbeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.trayheartbeat')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
